server:
  port: 8081
spring:
  application:
    name: "loan-applications-service"
  cloud:
    aws:
      region:
        static: us-east-2
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
data:
  r2dbc:
    repositories:
      enabled: true
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "crediya_loans_db"
    schema: "public"
    username: "root"
    password: "root"
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
springdoc:
  packages-to-scan: "co.com.powerup.api"
  paths-to-match: "/api/v1/**"
  webflux:
    core:
      fn:
        enabled: true
  api-docs:
    enabled: true
  show-actuator: true
logging:
  level:
    org.springframework.r2dbc.connection: "DEBUG"
    io.r2dbc.postgresql: "DEBUG"
adapter:
  restconsumer:
    timeout: 5000
    url: "http://localhost:8080"
  sqs:
    region: "us-east-2"
    queues:
      notification: "https://sqs.us-east-2.amazonaws.com/225989345826/loan-application-status-notifications"
      calculate-capacity: "https://sqs.us-east-2.amazonaws.com/225989345826/loan-application-calculate-capacity"
entrypoint:
  sqs:
    region: "us-east-2"
    queueUrl: "https://sqs.us-east-2.amazonaws.com/225989345826/loan-applications-results-queue"
    wait-time-seconds: 20
    visibility-timeout-seconds: 30
    max-number-of-messages: 10
    number-of-threads: 2
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
clients:
  user-service:
    base-url: "http://localhost:8080"

